name: shopping_list
description: A shopping list app.
publish_to: 'none'
version: 1.5.0+3

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1
  flutter_settings_ui: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  accessibility_tools: ^1.0.1
  flutter_speed_dial: ^7.0.0
  implicitly_animated_reorderable_list_2: ^0.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter_icons:
  android: true
  ios: true
  image_path: assets\icon\icon.png
  adaptive_icon_foreground: assets\icon\smaller_icon.png
  adaptive_icon_background: "#FFBD33"

flutter:
  uses-material-design: true
